#!/usr/bin/env python3
"""
Generate Separate ConfigMaps Per Entity Type

This script generates a kustomization.yaml with separate ConfigMaps for each
entity type, enabling selective job restarts when only specific data changes.

Usage:
    python3 generate-configmap-kustomization.py [--output kustomization.yaml]
"""

import argparse
from pathlib import Path
from typing import Dict, List, Tuple
import sys


# Wave-Based Mapping: configmap-name -> list of entity directories
# This consolidates multiple entities into wave-based ConfigMaps
WAVE_MAPPINGS = [
    # Wave 1: System Foundation (Waves 1-9) - 9 entities
    ('fineract-data-system-foundation', [
        'codes-and-values',           # code_values
        'offices',                     # offices
        'staff',                       # staff
        'roles',                       # roles
        'system-config/currency-config',      # currency_config
        'system-config/working-days',         # working_days
        'system-config/account-number-formats', # account_number_formats
        'system-config/maker-checker',        # maker_checker
        'system-config/scheduler-jobs',       # scheduler_jobs
    ]),

    # Wave 2: Products (Waves 10-20) - 11 entities
    ('fineract-data-products', [
        'products/loan-products',      # loan_products
        'notification-templates',      # notification_templates
        'data-tables',                 # data_tables
        'tellers',                     # tellers
        'reports',                     # reports
        'products/savings-products',   # savings_products
        'charges',                     # charges
        'collateral-types',            # collateral_types
        'guarantor-types',             # guarantor_types
        'floating-rates',              # floating_rates
        'delinquency/buckets',         # delinquency_buckets
    ]),

    # Wave 3: Accounting (Waves 21-29) - 9 entities
    ('fineract-data-accounting', [
        'accounting/chart-of-accounts',          # chart_of_accounts
        'accounting/fund-sources',               # fund_sources
        'accounting/payment-types',              # payment_types
        'accounting/tax-groups',                 # tax_groups
        'accounting/loan-provisioning',          # loan_provisioning
        'accounting/financial-activity-mappings', # financial_activity_mappings
        'accounting/loan-product-accounting',    # loan_product_accounting
        'accounting/savings-product-accounting', # savings_product_accounting
        'accounting/payment-type-accounting',    # payment_type_accounting
    ]),

    # Wave 4: Entities (Waves 30-34) - 5 entities
    ('fineract-data-entities', [
        'clients',                    # demo_clients
        'accounts/savings-accounts',  # demo_savings_accounts
        'accounts/loan-accounts',     # demo_loan_accounts
        'loans/loan-collateral',      # demo_loan_collateral
        'loans/loan-guarantors',      # demo_loan_guarantors
    ]),

    # Wave 5: Transactions (Waves 35-39) - 4 entities
    ('fineract-data-transactions', [
        'transactions/savings-deposits',    # demo_savings_deposits
        'transactions/savings-withdrawals', # demo_savings_withdrawals
        'transactions/loan-repayments',     # demo_loan_repayments
        'transactions/inter-branch-transfers', # demo_transfers
    ]),

    # Wave 6: Calendar (Wave 40) - 1 entity
    ('fineract-data-calendar', [
        'calendar/holidays',          # holidays
    ]),
]


def find_yaml_files(data_dir: Path, entity_dir: str) -> List[str]:
    """
    Find all YAML files for an entity type

    Args:
        data_dir: Base data directory (e.g., operations/fineract-data/data/dev)
        entity_dir: Entity subdirectory (e.g., 'products/loan-products')

    Returns:
        List of file paths relative to kustomization.yaml location
    """
    full_path = data_dir / entity_dir

    if not full_path.exists():
        return []

    yaml_files = sorted(full_path.glob('**/*.yaml'))

    # Filter out kustomization.yaml files (they're metadata, not data)
    yaml_files = [f for f in yaml_files if f.name != 'kustomization.yaml']

    # Return paths relative to kustomization.yaml (which is in operations/fineract-data/)
    return [f"data/dev/{entity_dir}/{f.relative_to(full_path)}" for f in yaml_files]


def generate_kustomization(data_dir: Path, jobs_dir: Path) -> str:
    """
    Generate kustomization.yaml content with separate ConfigMaps

    Args:
        data_dir: Base data directory
        jobs_dir: Directory containing job manifests

    Returns:
        kustomization.yaml content as string
    """
    lines = []

    # Header
    lines.append("# Auto-generated by generate-configmap-kustomization.py")
    lines.append("# DO NOT EDIT MANUALLY - Run the script to regenerate")
    lines.append("")
    lines.append("apiVersion: kustomize.config.k8s.io/v1beta1")
    lines.append("kind: Kustomization")
    lines.append("")

    # Namespace
    lines.append("namespace: fineract-dev")
    lines.append("")

    # Resources (job manifests)
    lines.append("resources:")
    job_files = sorted(jobs_dir.glob('job-*.yaml'))
    for job_file in job_files:
        # Skip backup files
        if job_file.name.endswith('.bak'):
            continue
        lines.append(f"- kubernetes/base/jobs/{job_file.name}")
    lines.append("")

    # ConfigMaps for data only (scripts are now in Docker image)
    lines.append("configMapGenerator:")
    lines.append("# Note: Loader scripts are now baked into the guymoyo/fineract-loader Docker image")
    lines.append("# Only data ConfigMaps are generated here")
    lines.append("")

    # Wave-based ConfigMaps (consolidating multiple entities per wave)
    total_waves = 0
    total_entity_dirs = 0
    waves_with_data = 0
    waves_without_data = 0
    total_yaml_files = 0

    for configmap_name, entity_dirs in WAVE_MAPPINGS:
        # Collect all YAML files for all entities in this wave
        all_wave_files = []
        for entity_dir in entity_dirs:
            yaml_files = find_yaml_files(data_dir, entity_dir)
            all_wave_files.extend(yaml_files)
            total_entity_dirs += 1

        total_waves += 1

        if not all_wave_files:
            waves_without_data += 1
            lines.append(f"# {configmap_name}: No data files found")
            continue

        waves_with_data += 1
        total_yaml_files += len(all_wave_files)

        lines.append(f"- name: {configmap_name}")
        lines.append("  files:")
        for yaml_file in sorted(all_wave_files):
            lines.append(f"  - {yaml_file}")
        lines.append("")

    # Summary comment at the end
    lines.append("# Summary:")
    lines.append(f"#   Total waves: {total_waves}")
    lines.append(f"#   Total entity directories: {total_entity_dirs}")
    lines.append(f"#   Waves with data: {waves_with_data}")
    lines.append(f"#   Waves without data: {waves_without_data}")
    lines.append(f"#   Total YAML files: {total_yaml_files}")
    lines.append(f"#   Total ConfigMaps: {waves_with_data} (data only, scripts in Docker image)")

    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(
        description='Generate kustomization.yaml with separate ConfigMaps per entity'
    )
    parser.add_argument(
        '--output',
        default='kustomization-new.yaml',
        help='Output file path (default: kustomization-new.yaml)'
    )
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Print output without writing file'
    )

    args = parser.parse_args()

    # Determine paths
    script_dir = Path(__file__).parent
    fineract_data_dir = script_dir.parent
    data_dir = fineract_data_dir / 'data' / 'dev'
    jobs_dir = fineract_data_dir / 'kubernetes' / 'base' / 'jobs'

    print("=" * 80)
    print("FINERACT DATA CONFIGMAP GENERATOR")
    print("=" * 80)
    print(f"\nData directory: {data_dir}")
    print(f"Jobs directory: {jobs_dir}")
    print(f"Output file: {args.output}")
    print(f"Dry run: {args.dry_run}\n")

    if not data_dir.exists():
        print(f"ERROR: Data directory not found: {data_dir}")
        sys.exit(1)

    if not jobs_dir.exists():
        print(f"ERROR: Jobs directory not found: {jobs_dir}")
        sys.exit(1)

    # Generate content
    content = generate_kustomization(data_dir, jobs_dir)

    if args.dry_run:
        print("=" * 80)
        print("GENERATED CONTENT (DRY RUN)")
        print("=" * 80)
        print(content)
    else:
        output_path = fineract_data_dir / args.output
        output_path.write_text(content)
        print(f"✓ Generated: {output_path}")
        print(f"\nFile size: {len(content)} bytes")
        print(f"Lines: {len(content.splitlines())}")

        # Count ConfigMaps
        configmap_count = content.count('- name: fineract-data-')
        print(f"ConfigMaps generated: {configmap_count}")

        print("\n" + "=" * 80)
        print("NEXT STEPS")
        print("=" * 80)
        print("\n1. Review the generated file:")
        print(f"   cat {output_path}")
        print("\n2. Compare with current kustomization.yaml:")
        print(f"   diff {fineract_data_dir}/kustomization.yaml {output_path}")
        print("\n3. Test with kustomize build:")
        print(f"   cd {fineract_data_dir} && kustomize build . | grep 'kind: ConfigMap' | wc -l")
        print("\n4. If satisfied, replace current kustomization.yaml:")
        print(f"   mv {output_path} {fineract_data_dir}/kustomization.yaml")
        print("\n5. Update job YAML files to reference new ConfigMap names:")
        print("   python3 scripts/update-job-configmaps.py")


if __name__ == '__main__':
    main()
