#!/bin/bash
#
# Sync Fineract API Schemas
#
# This script extracts the OpenAPI schema from Fineract source code
# and copies it to the GitOps repository for schema management.
#
# Usage:
#   ./sync-fineract-schemas.sh [--build]
#
# Options:
#   --build    Force rebuild of Fineract to generate fresh OpenAPI spec
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Directories
FINERACT_DIR="${FINERACT_DIR:-/Users/guymoyo/dev/fineract}"
GITOPS_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SCHEMA_DIR="$GITOPS_DIR/schemas"

# OpenAPI spec location (generated by Fineract build)
OPENAPI_SOURCE="$FINERACT_DIR/fineract-provider/build/classes/java/main/static/fineract.json"
OPENAPI_DEST="$SCHEMA_DIR/fineract-openapi.json"

echo -e "${BLUE}============================================${NC}"
echo -e "${BLUE}Fineract Schema Sync${NC}"
echo -e "${BLUE}============================================${NC}"
echo ""

# Check if Fineract directory exists
if [ ! -d "$FINERACT_DIR" ]; then
    echo -e "${RED}✗ Fineract directory not found: $FINERACT_DIR${NC}"
    echo -e "${YELLOW}  Set FINERACT_DIR environment variable to point to Fineract source${NC}"
    exit 1
fi

echo -e "${GREEN}✓${NC} Fineract directory: $FINERACT_DIR"

# Check if we need to build
NEED_BUILD=false
if [ "$1" == "--build" ]; then
    NEED_BUILD=true
    echo -e "${YELLOW}ℹ${NC} Force build requested"
elif [ ! -f "$OPENAPI_SOURCE" ]; then
    NEED_BUILD=true
    echo -e "${YELLOW}ℹ${NC} OpenAPI spec not found, build required"
fi

# Build Fineract if needed
if [ "$NEED_BUILD" == "true" ]; then
    echo ""
    echo -e "${BLUE}📦 Building Fineract...${NC}"
    echo -e "${YELLOW}   This may take several minutes...${NC}"

    cd "$FINERACT_DIR"

    # Build only the provider module (faster than full build)
    if ./gradlew :fineract-provider:build -x test -x integrationTest 2>&1 | tail -20; then
        echo -e "${GREEN}✓${NC} Fineract build completed"
    else
        echo -e "${RED}✗ Fineract build failed${NC}"
        exit 1
    fi

    cd - > /dev/null
else
    echo -e "${GREEN}✓${NC} OpenAPI spec already exists"
fi

# Verify OpenAPI spec exists
if [ ! -f "$OPENAPI_SOURCE" ]; then
    echo -e "${RED}✗ OpenAPI spec not found after build: $OPENAPI_SOURCE${NC}"
    echo -e "${YELLOW}  Try running with --build flag${NC}"
    exit 1
fi

echo -e "${GREEN}✓${NC} OpenAPI spec found: $OPENAPI_SOURCE"

# Get file size and modification time
SPEC_SIZE=$(du -h "$OPENAPI_SOURCE" | cut -f1)
SPEC_MODIFIED=$(stat -f "%Sm" -t "%Y-%m-%d %H:%M:%S" "$OPENAPI_SOURCE" 2>/dev/null || stat -c "%y" "$OPENAPI_SOURCE" 2>/dev/null || echo "unknown")

echo -e "${BLUE}   Size:${NC} $SPEC_SIZE"
echo -e "${BLUE}   Modified:${NC} $SPEC_MODIFIED"

# Create schema directory if it doesn't exist
mkdir -p "$SCHEMA_DIR"

# Copy OpenAPI spec to GitOps repo
echo ""
echo -e "${BLUE}📋 Copying OpenAPI spec...${NC}"

if cp "$OPENAPI_SOURCE" "$OPENAPI_DEST"; then
    echo -e "${GREEN}✓${NC} Copied to: $OPENAPI_DEST"
else
    echo -e "${RED}✗ Failed to copy OpenAPI spec${NC}"
    exit 1
fi

# Check if there are changes
cd "$GITOPS_DIR"

if git diff --quiet "$OPENAPI_DEST" 2>/dev/null; then
    echo ""
    echo -e "${GREEN}✓ No schema changes detected${NC}"
    echo -e "${YELLOW}  OpenAPI spec is up to date${NC}"
else
    echo ""
    echo -e "${YELLOW}⚠ Schema changes detected!${NC}"
    echo ""
    echo -e "${BLUE}Changes:${NC}"
    git diff --stat "$OPENAPI_DEST" 2>/dev/null || echo "  (new file)"
    echo ""
    echo -e "${YELLOW}Next steps:${NC}"
    echo -e "  1. Review changes: ${BLUE}git diff $OPENAPI_DEST${NC}"
    echo -e "  2. Test with existing YAML files"
    echo -e "  3. Update loaders if API changes require it"
    echo -e "  4. Commit changes: ${BLUE}git add $OPENAPI_DEST && git commit${NC}"
fi

echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}Schema sync completed successfully!${NC}"
echo -e "${GREEN}============================================${NC}"
