#!/usr/bin/env python3

import os
import yaml
from pathlib import Path
from collections import defaultdict

# Define the mapping from top-level directories to ConfigMaps
# Based on the job structure and execution order (wave annotations)
CONFIGMAP_MAPPING = {
    'fineract-data-system-foundation': [
        'codes-and-values',
        'offices',
        'staff',
        'roles'
    ],
    'fineract-data-products': [
        'charges',
        'products',  # includes loan-products and savings-products subdirs
        'collateral-types',
        'guarantor-types',
        'floating-rates',
        'delinquency',
        'notification-templates',
        'data-tables',
        'reports',
        'tellers',
        'system-config'
    ],
    'fineract-data-accounting': [
        'accounting'
    ],
    'fineract-data-entities': [
        'clients',
        'accounts'  # includes savings-accounts and loan-accounts
    ],
    'fineract-data-transactions': [
        'loans',
        'transactions'
    ],
    'fineract-data-calendar': [
        'calendar'
    ]
}

def generate_kustomization():
    """Generate kustomization.yaml with all existing YAML files"""

    kustomization = {
        'apiVersion': 'kustomize.config.k8s.io/v1beta1',
        'kind': 'Kustomization',
        'namespace': 'fineract-dev',
        'resources': ['kubernetes/base'],
        'generatorOptions': {
            'disableNameSuffixHash': True
        },
        'configMapGenerator': []
    }

    base_dir = Path('data/dev')

    for configmap_name, top_dirs in CONFIGMAP_MAPPING.items():
        files = []

        for top_dir in top_dirs:
            dir_path = base_dir / top_dir
            if dir_path.exists():
                # Recursively find all YAML files in this directory and subdirectories
                yaml_files = sorted(dir_path.rglob('*.yaml'))

                for yaml_file in yaml_files:
                    # Skip kustomization.yaml files
                    if yaml_file.name == 'kustomization.yaml':
                        continue

                    # Create the file mapping in format: key=path
                    # Key includes relative path from top-level dir to ensure uniqueness
                    # e.g., "notification-templates/client-activation.yaml" vs "system-config/client-activation.yaml"
                    relative_path = yaml_file.relative_to(dir_path.parent)
                    key = str(relative_path).replace('/', '__')  # Replace / with __ for valid ConfigMap key
                    path = str(yaml_file)
                    files.append(f"{key}={path}")

        if files:
            configmap = {
                'name': configmap_name,
                'files': files
            }
            kustomization['configMapGenerator'].append(configmap)

    # Write the kustomization.yaml
    with open('kustomization.yaml', 'w') as f:
        f.write("# Auto-generated by fix-kustomization.py - DO NOT EDIT MANUALLY\n")
        f.write("# Run ./fix-kustomization.py to regenerate\n")
        f.write("# Generated with disableNameSuffixHash to prevent hash suffixes\n\n")
        yaml.dump(kustomization, f, default_flow_style=False, sort_keys=False, width=1000)

    print(f"Generated kustomization.yaml with {len(kustomization['configMapGenerator'])} ConfigMaps")
    print(f"\nConfigMap Summary:")

    total_files = 0
    for cm in kustomization['configMapGenerator']:
        file_count = len(cm['files'])
        total_files += file_count
        print(f"  - {cm['name']}: {file_count} files")

    print(f"\nTotal files: {total_files}")

if __name__ == '__main__':
    # Change to the script's directory
    script_dir = Path(__file__).parent
    os.chdir(script_dir)

    generate_kustomization()
